function Jv_DH = Jv_DH_Function(theta1,theta2,theta3,a1,a2,a3)
%Jv_DH_Function
%    Jv_DH = Jv_DH_Function(THETA1,THETA2,THETA3,A1,A2,A3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    29-Dec-2024 17:32:48

t2 = theta1+theta2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+theta3;
t6 = cos(t5);
t7 = sin(t5);
t8 = a2.*t3;
t9 = a2.*t4;
t10 = -t9;
t11 = (a3.*t6)./2.0;
t12 = (a3.*t7)./2.0;
t13 = -t12;
Jv_DH = reshape([t10+t13-a1.*sin(theta1),t8+t11+a1.*cos(theta1),0.0,t10+t13,t8+t11,0.0,t13,t11,0.0],[3,3]);
