function Jw_DH = Jw_DH_Function(theta1,theta2,theta3,a1,a2,a3)
%Jw_DH_Function
%    Jw_DH = Jw_DH_Function(THETA1,THETA2,THETA3,A1,A2,A3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    29-Dec-2024 17:32:48

Jw_DH = reshape([0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0],[3,3]);
